# fly.toml app configuration file generated for pricething-redis on 2024-10-20T19:24:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pricething-redis'
primary_region = 'arn'

[build]

[[mounts]]
  source = 'redis_server'
  destination = '/data'

[http_service]
  internal_port = 6379
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 6379
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  [[services.ports]]
    port = 6379

[[vm]]
  size = 'shared-cpu-1x'

[[metrics]]
  port = 9091
  path = '/metrics'
