# fly.toml app configuration file generated for vernissage-redis on 2024-10-16T08:04:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pricething-redis'
primary_region = 'arn'

[build]
image = 'redis/redis-stack-server:latest'

[mounts]
destination = "/data"
source = "redis_server"

[metrics]
port = 9091
path = "/metrics"

[[services]]
internal_port = 6379
protocol = "tcp"
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
[[services.ports]]
port = 6379

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 2
